name: e3sm-diags

on:
  merge_group:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'e3sm-diags/**'
      - '.github/workflows/e3sm-diags.yaml'
  push:
    branches: [ main ]
    paths:
      - 'e3sm-diags/**'
      - '.github/workflows/e3sm-diags.yaml'
    tags:
      - 'e3sm-diags-*'

jobs:
  ocis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          show-progress: false
          persist-credentials: false
      -
        name: GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}-e3sm-diags
      -
        name: QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Push
        uses: docker/build-push-action@v6
        with:
          context: e3sm-diags/
          file: e3sm-diags/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
