name: inputdata

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'inputdata/**'
      - '.github/workflows/inputdata.yaml'
  push:
    branches: [ main ]
    paths:
      - 'inputdata/**'
      - '.github/workflows/inputdata.yaml'
    tags:
      - 'inputdata-*'

jobs:
  ocis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        data:
          - files

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          show-progress: false
          persist-credentials: false
      -
        name: GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}-inputdata-${{ matrix.data }}
      -
        name: QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Push
        uses: docker/build-push-action@v6
        with:
          context: inputdata/
          file: inputdata/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DATA_FILE=${{ matrix.data }}.txt
