name: ghci-standalone

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'standalone-ghci/**'
      - '.github/workflows/standalone-ghci.yaml'
  push:
    branches: [ main ]
    paths:
      - 'standalone-ghci/**'
      - '.github/workflows/standalone-ghci.yaml'
    tags:
      - 'standalone-ghci-*'

env:
  GCC_VERSION: "11.4.0"
  MPICH_VERSION: "4.2.3"
  SZIP_VERSION: "2.1.1"
  HDF5_VERSION: "1.12.3"
  NETCDFC_VERSION: "4.9.2"
  NETCDFCXX_VERSION: "4.2"
  NETCDFFORTRAN_VERSION: "4.6.1"
  PNETCDF_VERSION: "1.12.3"

jobs:
  ocis:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          show-progress: false
          persist-credentials: false
      -
        name: GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}-standalone-ghci
      -
        name: QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Push
        uses: docker/build-push-action@v6
        with:
          context: standalone-ghci/
          file: standalone-ghci/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GCC_VERSION=${{ env.GCC_VERSION }}
            MPICH_VERSION=${{ env.MPICH_VERSION }}
            SZIP_VERSION=${{ env.SZIP_VERSION }}
            HDF5_VERSION=${{ env.HDF5_VERSION }}
            NETCDFC_VERSION=${{ env.NETCDFC_VERSION }}
            NETCDFCXX_VERSION=${{ env.NETCDFCXX_VERSION }}
            NETCDFFORTRAN_VERSION=${{ env.NETCDFFORTRAN_VERSION }}
            PNETCDF_VERSION=${{ env.PNETCDF_VERSION }}
